name: "Bridget O'Brien project 2014"
description: "Philippines"

permalink: pretty

exclude: [README.md]

# Development settings. Override these in _config_production.yml
production: false
url: "http://localhost:4000"
